### ISSUE TITLE
Tests Scheme

### ISSUE THREAD

**Issue by safaairaq100** [yigityus/ASTM#4]
Thank you for the code it's very helpful.
I have a question, the tests that ASTM device need to know the test information, I have test code (ex: SLTFT ) and SCode  (ex: TFT).  and have another table contains ParamterCode
[ DBSS, RERF, THYR, HSDG, TRII ] as foreign table 
 
`
        static void SerialWrite()
           {
            wh = new AutoResetEvent(false);

            Message m = new Message(_barcode);

            string sql = "select C.CIHAZ_TEST from CHZ_ORDER O, CHZ_TEST C where O.TUBE_BARCODE=" +
                _barcode.ToString() + "and C.CIHAZ_ID=" + cihazId + "and C.LIS_TEST=O.LIS_TEST and O.PENDING='P'";
            
            OracleCommand cmd = new OracleCommand(sql, conn);
            List<string> tests = new List<string>();
            OracleDataReader read;
            try
            {
                conn.Open();
                read = cmd.ExecuteReader();

                while (read.Read())
                {
                    tests.Add(read[0].ToString());
                }

            }

            catch (OracleException OEx)
            {
                Console.WriteLine(OEx.Message);
            }
            finally
            {
                conn.Close();
                cmd.Dispose();
            }
 

            string[] send = m.SendOrder(tests);

            for (int i = 0; i < send.Length; i++)
            {
                sp.Write(send[i]);
                wh.WaitOne();
            }

            Console.WriteLine("[Host ~]$ ordered: {0}", "tests");
        }`

so what I send in    **sp.Write(send[i]);** ?

**Comment by yigityus** [comment]
It depends on your medical instruments communication protocol. In my demo case, that was only the code of the tests. It may differ accordingly.
Thank you.

**Comment by safaairaq100** [comment]
> It depends on your medical instruments communication protocol. In my demo case, that was only the code of the tests. It may differ accordingly.
> Thank you.

When send [ENQ] I got [ACK], after that, I send the header :
 < STX >1H|\^&||||||||ARCHITECT^8.10^F3450004006^H1P1O1R1C1Q1L1||P|< CR >< ETX >
the device respond with [NACK] . what I missing ?

[This Message I Send](https://ibb.co/K7cfgpB)

**Comment by safaairaq100** [comment]
the problem was solved, I added checksum, and edit the order .

`  public class Message
    {
        static string soh = char.ConvertFromUtf32(1);
        static string stx = char.ConvertFromUtf32(2);
        static string etx = char.ConvertFromUtf32(3);
        static string eot = char.ConvertFromUtf32(4);
        static string enq = char.ConvertFromUtf32(5);
        static string ack = char.ConvertFromUtf32(6);
        static string nack = char.ConvertFromUtf32(21);
        static string etb = char.ConvertFromUtf32(23);
        static string lf = char.ConvertFromUtf32(10);
        static string cr = char.ConvertFromUtf32(13);

        char recordType;
        const char pipe = '|';
        const char caret = '^';
        string delimiterDef = @"|\^&";


        string _instrument = "";
        string host = "";



        private string _barcode;

        public string Barcode
        {
            get { return _barcode; }
            set { _barcode = value; }
        }



        /// <summary>
        /// Reads checksum of an ASTM frame, calculates characters after STX,
        /// up to and including the ETX or ETB. Method assumes the frame contains an ETX or ETB.
        /// </summary>
        /// <param name="frame">frame of ASTM data to evaluate</param>
        /// <returns>string containing checksum</returns>
        public string GetCheckSumValue(string frame)
        {
            string checksum = "00";

            int byteVal = 0;
            int sumOfChars = 0;
            bool complete = false;

            //take each byte in the string and add the values
            for (int idx = 0; idx < frame.Length; idx++)
            {
                byteVal = Convert.ToInt32(frame[idx]);

                switch (byteVal)
                {
                    case ControlCodes.STX:
                        sumOfChars = 0;
                        break;
                    case ControlCodes.ETX:
                    case ControlCodes.ETB:
                        sumOfChars += byteVal;
                        complete = true;
                        break;
                    default:
                        sumOfChars += byteVal;
                        break;
                }

                if (complete)
                    break;
            }

            if (sumOfChars > 0)
            {
                //hex value mod 256 is checksum, return as hex value in upper case
                checksum = Convert.ToString(sumOfChars % 256, 16).ToUpper();
            }

            //if checksum is only 1 char then prepend a 0
            return (string)(checksum.Length == 1 ? "0" + checksum : checksum);
        }



        public Message(string barcode,string instrument)
        {
            _barcode = barcode;
            _instrument = instrument;
        }


        public string[] SendOrder(List<string> tests)
        {
            string[] send = new string[6];

            send[0] = enq;
            send[1] = Header();
            send[2] = Patient(_barcode, 30, 'M');
            send[3] = Order(_barcode, tests);
            send[4] = Terminator();
            send[5] = eot;

            return send;
        }


        public string Header()
        {
            string record;
            recordType = 'H';

            record = "1" + recordType + delimiterDef + new String(pipe, 5) + host + new String(pipe, 3) + _instrument +
                     new String(pipe, 2) + "P" + pipe + "1";
            record = stx + record + cr + etx;
        
            return record + GetCheckSumValue(record)+cr+lf;
        }

        public string Patient(string barcode, int age, char sex)
        {
            string record;
            recordType = 'P';

            record = "2" + recordType + pipe + "1" + new String(pipe, 2) + barcode.ToString() + new String(pipe, 5) +
                     sex + new String(pipe, 6) + age.ToString() + caret + "Y";
            record = record + cr + etx;
       

            record = stx + record;
            return record + GetCheckSumValue(record) + cr + lf; ;
        }
        //instrumentSpecimenID
        //comes with the query string was sent
        //<Sample No>^<Rack ID>^<Position No>^^<RackType>^<Container Type>

        virtual public string Order(string barcode, List<string> tests)
        {
            string record;
            string testRecord = "";
            recordType = 'O';

            foreach (string test in tests)
            {
                testRecord += new String(caret, 3)+test + @"\";
            }

            if (testRecord != "")
            {
                testRecord = testRecord.Substring(0, testRecord.Length - 1); //trim the last backslash
            }


            record = "3" + recordType + pipe + "1" + pipe + barcode + pipe + pipe + testRecord + pipe +
                     "R" /*priority {R, S}*/ +
                     new String(pipe, 6) + "N" + //action code {N, new C, cancel}
                     new String(pipe, 14) + "O" + //order record 
                     new String(pipe, 5);

            record = record + cr + etx;
            record = stx + record;
            return record + GetCheckSumValue(record) + cr + lf; ;
        }
        public string Terminator()
        {
            string record;
            recordType = 'L';

            record = "4" + "L" + pipe + "1" + pipe + "N";
            record = record + cr + etx; //no checksum.. add [##+cr+lf] if you want...
            record = stx + record;
            return record + GetCheckSumValue(record) + cr + lf; ;
        }

     

      
    }`

**Comment by yigityus** [comment]
👍
